sudo: required

language: python

services:
  - docker

install:
  - git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
  - git fetch --no-tags
  - git checkout $TRAVIS_BRANCH
  - git pull origin $TRAVIS_BRANCH
  - sh init-mock-setup.sh
  - sh prepare.sh
  - sh init-all.sh
  - git remote set-url origin https://${GHTOKEN}@github.com/GreenSense/Index.git

script:
  - sh update-submodules.sh
  - sh build-tests.sh
  - sh test.sh
